[package]
name = "dyspxkrypt-libuefi"
description = "Raw bindings of UEFI that conforms to the definitions of the UEFI Specification."
categories = ["external-ffi-bindings", "no-std"]
version = "0.2.0-alpha.4"
edition = "2021"
authors = ["HTGAzureX1212."]
readme = "README.md"
license = "GPL-3.0-only"
documentation = "https://docs.rs/dyspxkrypt-libuefi"
repository = "https://github.com/dyspxkrypt-os/dyspxkrypt-libuefi/"

[dependencies]

[features]
default = []
full = ["console-full", "dev-path-full", "image-full", "media-full"]

console-full = ["console", "console-gop", "console-pointer", "console-serial", "console-serial-v1p1"]
console = []
console-gop = []
console-serial = []
console-serial-v1p1 = []
console-pointer = []

dev-path-full = []

image-full = ["image", "image-dev-path"]
image = []
image-dev-path = []

media-full = ["media-file-v2", "media-fs"]
media-file = []
media-file-v2 = []
media-fs = ["media-file-v2"]

[package.metadata.docs.rs]
all-features = true
