[package]
name = "dyspxkrypt-libuefi"
description = "Raw bindings of UEFI that conforms to the definitions of the UEFI Specification."
categories = ["external-ffi-bindings", "no-std"]
version = "0.2.0-alpha.3"
edition = "2021"
authors = ["HTGAzureX1212."]
readme = "README.md"
license = "GPL-3.0-only"
documentation = "https://docs.rs/dyspxkrypt-libuefi"
repository = "https://github.com/dyspxkrypt-os/dyspxkrypt-libuefi/"

[dependencies]

[features]
default = []
full = ["console-full", "image"]

console-full = ["console", "console-gop", "console-pointer", "console-serial"]
console = []
console-gop = []
console-serial = []
console-pointer = []

image-full = ["image", "image-dev-path"]
image = []
image-dev-path = []

media-full = ["media-file"]
media-file = []

[package.metadata.docs.rs]
all-features = true
