[package]
name = "dyspxkrypt-libuefi"
description = "Raw bindings of UEFI that conforms to the definitions of the UEFI Specification."
categories = ["external-ffi-bindings", "no-std"]
version = "0.1.0-alpha.3"
edition = "2021"
authors = ["HTGAzureX1212."]
readme = "README.md"
license = "GPL-3.0-only"
documentation = "https://docs.rs/dyspxkrypt-libuefi"
repository = "https://github.com/dyspxkrypt-os/dyspxkrypt-libuefi/"

[dependencies]
